### ISSUE TITLE
AttributeError: 'int' object has no attribute 'start'

### ISSUE THREAD

**Issue by good-point-lab** [rbaltrusch/pygame_examples#2]
Running the event.py example in Python 3.10.1 / OSX 12.1 getting an error in line 37, in __post_init__
    self.timer.start()
AttributeError: 'int' object has no attribute 'start'

**Comment by rbaltrusch** [comment]
Hello @good-point-lab , thanks for raising the issue.

This seems to have been left over from slightly rewriting the event handling in the Entity class. I have fixed it in commit 69771b0 and added a blinking screen event to better showcase the functionality in commit 7dda0b9 (current HEAD).

Best,
Richard

**Comment by good-point-lab** [comment]
Hi Richar,
Just confirming - everything works. Thank you!  I am interested in using
the library with rotary encoders, buttons, and other analog inputs for
SDRs.  Your examples could help me to integrate GPIO events with UI.   If
you know good examples of using PyGame with RPI GPIO, please let me know.

Alex Greysukh

**Comment by rbaltrusch** [comment]
Hi Alex, 

All I know about SDR is that I read an article about it some 10 years ago :) I havent done pygame on Raspberry Pi yet, but from already came across various forum posts of people that did, so it seems to be possible and used quite a bit. It shouldn't be too hard to interface with the hardware you are describing if wrapping it in a hardware interface, which you then speak to using pygame, although it's been a little while that I've dealt with a hardware project :)

Good luck with your project - if you have any Python or pygame specific issues or questions, drop me a mail 👍 

Best,
Richard
